xb_promo/urls.py
from . import views
from django.urls import path

urlpatterns = [
     path('', views.Feature.as_view(), name='home'),
     path('<slug:slug>', views.Feature.as_view(), name='feature_page'),
     path('issues/', views.IssueDisplay.as_view(), name='issue_display'),
     path('issues/<int:issue_num>/<int:answer_num>/<str:search_field>/\
<int:scroll_to_answer>/<int:scroll_delay>',
          views.IssueDisplay.as_view(), name='step_issue'),
     path('edit_issue/<int:edit>/<int:issue_num>/\
<str:search_field>/<int:issue_id>/',
          views.IssueEdit.as_view(), name='edit_issue'),
     path('add_issue/', views.IssueAdd.as_view(), name='add_issue'),
     path('delete_issue/<int:issue_id>/', views.delete_issue,
          name='delete_issue'),
     path('add_answer/<int:issue_id>/', views.AnswerAdd.as_view(),
          name="add_answer"),
     path('edit_answer/<int:issue_id>/<int:answer_id>/',
          views.AnswerEdit.as_view(), name="edit_answer"),
     path('delete_answer/<int:issue_id>/<int:answer_id>/',
          views.delete_answer, name='delete_answer'),
     path('dump_database/', views.DumpDatabase.as_view(), name='dump_database')
]

xbasic_promo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('xb_promo.urls'), name='xb_promo_urls'),
    path('accounts/', include('allauth.urls')),
]

xb_promo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django_summernote.widgets import SummernoteWidget
from cloudinary.forms import CloudinaryJsFileField
from .models import Issue, Answer


class IssueForm(forms.ModelForm):

    class Meta:
        model = Issue
        fields = (
            'title',
            'description',
            'keywords',
            'content',
            'screenshot_img'
        )

    widgets = {
        'content': SummernoteWidget(),
    }
    title = forms.CharField(widget=forms.
                            TextInput(attrs={'style': 'width: 40%',
                                             'aria-label': 'title'}))
    description = forms.CharField(
        widget=forms.TextInput(attrs={'style': 'width: 80%',
                                      'aria-label': 'description'})
    )
    keywords = forms.CharField(
        widget=forms.TextInput(attrs={'style': 'width: 81%',
                                      'aria-label': 'keywords'})
    )
    content = forms.CharField(widget=forms.
                              Textarea(attrs={'aria-label': 'content'}))


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = (
            'title',
            'content',
            'screenshot_img'
        )

    widgets = {
        'content': SummernoteWidget(),
    }

    title = forms.CharField(widget=forms.
                            TextInput(attrs={'style': 'width: 40%'}))

templates/answer_panel.html
<div class="container-fluid issue_panel mb-3">
    <div class="row">
        <div class="col-12 col-md-6">
            <p><strong>Title: </strong>{{ answer.title }}</p>
        </div>
        <div class="col-md-1"></div>
        <div class="col-12 col-md-5 text-md-right">
            <p><strong>Author: </strong>{{ answer.author }}</p>
            <p><strong>Date: </strong>{{ answer.date_submitted|date:"d/m/Y" }}</p>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-12 text-center">
            <p><strong>CONTENT</strong></p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ answer.content|safe }}
        </div>
    </div>
    {% if 'placeholder' not in answer.screenshot_img.url %}
    <div class="row">
        <div class="col-12">
            <img class="screenshot-img" src="{{ answer.screenshot_img.url }}" alt="Screenshot" width="100" height="100">
        </div>
    </div>
    {% endif %}
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="XBasic programming language and issues pages">
    <meta name="keywords" content="XBasic, programming language">
    <meta name="author" content="Robin Warner">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css" rel="stylesheet">
    

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>XBasic Promo</title>

<style>
 .logo {
    height: 200px;
    background: url( "https://res.cloudinary.com/dye9ynxxb/image/upload/v1680543486/logo_oxsmdr.webp" );
    background-size: 160px;
    background-repeat: no-repeat;
    background-position: center;
    background-color: cyan;
}

.site-intro-section {
    height: 420px;
    background: url( "{{ feature_page.intro_image.url }}" );
    background-repeat: no-repeat;
    background-size: cover;
    background-position: left top;
}

</style>
</head>

<body>
    <!-- Banner Head and Menu-->
    <header class="container-fluid">
        <div class="row">
                <div class="col-6 col-sm-4 col-md-3 col-lg-2 logo">
                    <a class="logo-link" href="{% url 'home' %}" aria-label="Link to Home Page"></a>
                </div>
            <div class="col-6 col-sm-8 col-md-9 col-lg-10">
                <div class="row site-heading-bar text-right">
                    <div class="col-12">
                        <h1>XBasic Promo</h1>
                    </div>
                </div>
                <!-- Menu -->
                <div class="row menu-bar bg-color-menu">
                    <div class="col-12 menu-col">
                        <nav class="navbar navbar-expand-lg navbar-light menu-block bg-color-menu">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                            </button>
                            
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                              <ul class="navbar-nav ml-auto">
                                <li class="nav-item active menu-item">
                                  <a class="nav-link" href="{% url 'feature_page' 'gui-design' %}">GUI-Design</a>
                                </li>
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'feature_page' 'language' %}">Language</a>
                                </li>
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'feature_page' 'functions' %}">Functions</a>
                                </li>
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'feature_page' 'debugging' %}">Debugging</a>
                                </li>
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'issue_display' %}?t={{ timestamp }}">Issues</a>
                                </li>
                                {% if user.is_authenticated %}
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                                </li>
                                {% else %}
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'account_login' %}">Sign-in/up</a>
                                </li>
                                {% endif %}
                                {% if user.is_superuser %}
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'dump_database' %}">Dump Database</a>
                                </li>
                                {% endif %}
                                <li class="nav-item active menu-item">
                                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                                </li>
                              </ul>
                            </div>
                          </nav>  
                    </div>
                </div>
            </div>
        </div>

    </header>

    <!-- Message Status Bar -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
                    fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" 
                        data-bs-dismiss="alert" aria-label="Close">
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock content %}

    <footer class="container-fluid">
        <div class="row footer-bar">
            <div class="col-3 footer-link-div text-center">
                <div class="footer-link-block">
                    <a href="https://narayana-art.co.uk/XBManual" target="_blank">
                        <img src="https://res.cloudinary.com/dye9ynxxb/image/upload/v1680544869/logo-small_hguofe.webp" width="40" height="40" alt="XBasic Logo">
                        XBasic Manual
                    </a>
                </div>
            </div>
            <div class="col-3 footer-link-div text-center">
                <div class="footer-link-block">
                    <a href="https://sourceforge.net/projects/xbasic/" target="_blank">
                        <img src="https://res.cloudinary.com/dye9ynxxb/image/upload/v1680544417/sourceforge-icon_ryuprq.webp" width="40" height="40" alt="Sourceforge">
                        Sourceforge Download
                    </a>
                </div>
            </div>
            <div class="col-3 footer-link-div text-center">
                <div class="footer-link-block">
                    <a href="https://github.com/xbwlteam" target="_blank">
                        <i class="fa fa-github"></i>
                        GitHub Download
                    </a>
                </div>
            </div>
            <div class="col-3 footer-link-div text-center">
                <div class="footer-link-block">
                    <a href="https://groups.io/g/MaxReasonsxBasic/topics?p=,,,0,0,0,0" target="_blank">
                        <img src="https://res.cloudinary.com/dye9ynxxb/image/upload/v1680544633/groups.io-logo_cdjtcl.webp" width="40" height="40" alt="Groups.io Logo">
                        XBUser Group
                    </a>
                </div>
            </div>
       </div>
    </footer>

    <script src="https://kit.fontawesome.com/8b758f6b51.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs4.min.js"></script>

    <script>
        var scroll_to_answer;
        var scroll_delay;

        $(document).ready(function() {
            $('#id_content').summernote();

            $('#deleteIssueButton').click(function() {
                deleteItemUrl = deleteIssueUrl;
                $('#confirmationModal').data('url', deleteItemUrl);
                $('#confirmationModal').modal('show');
            });

            $('#deleteAnswerButton').click(function() {
                deleteItemUrl = deleteAnswerUrl;
                $('#confirmationModal').data('url', deleteItemUrl);
                $('#confirmationModal').modal('show');
            });

            $('#confirmButton').click(function() {
                console.log("Got to confirm delete", deleteItemUrl)
                $.ajax({
                    url: deleteItemUrl,
                    method: 'POST',
                    cache: false,
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'issue_id': issueId
                    },
                    success: function(data) {
                        // Does not return to this, redirected
                        window.location.href = data.redirect_url;
                    },
                    error: function() {
                        // show an error message or handle the error
                        console.log("Had a delete item error");
                    }
                });
                $('#confirmationModal').modal('hide');
            });

            setTimeout(function () {
				let messages = document.getElementById("msg");
				let alert = new bootstrap.Alert(messages);
				alert.close();
			}, 10000);

        });

        $(window).on("load", function() {
            setTimeout( function () {
                if (scroll_to_answer) {
                    e = document.getElementById('answerTitle');
                    e.scrollIntoView();
                }
            }, scroll_delay);
        })   

    </script>
      
</body>
</html>

templates/dump_database.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h3>Database Dumped</h3>
            </div>
        </div>
    </div>
{% endblock content %}

templates/edit_answer.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <!-- Issue Panel for reference -->
    <div class="row">
        <div class="col-12 text-center">
            <h3>Add or Edit Answer</h3>
        </div>
        <div class="col-12 text-center">
            <h3>Issue for Reference</h3>
        </div>
    </div>
    {% include "issue_panel.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <h3>Your Answer</h3>
        </div>
    </div>
    {% if edit %}
    <form class="edit_form" method="post" enctype="multipart/form-data" action="{% url 'edit_answer' issue_id=issue_id answer_id=answer_id %}">
    {% else %}
    <form class="edit_form" method="post" enctype="multipart/form-data" action="{% url 'add_answer' issue_id=issue_id %}">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <div class="col-4 col-lg-2">
                <button type="submit" class="btn-edit-submit">Submit</button>
            </div>
        </div>
    </form>

</div>
{% endblock content %}

templates/edit_issue.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <h2>Issue</h2>
        </div>
    </div>
    {% if edit == 1 %}
    <form class="edit_form" method="post" enctype="multipart/form-data" action="{% url 'edit_issue' edit=1 issue_num=issue_num search_field=search_field issue_id=issue_id %}">
    {% else %}
    <form class="edit_form" method="post" enctype="multipart/form-data" action="{% url 'add_issue' %}">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
            <div class="col-4 col-lg-2">
                <button type="submit" class="btn-edit-submit">Submit</button>
            </div>
        </div>
    </form>
 </div> 

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="feature-page-heading">
    <h2>{{ feature_page.page_title }}</h2>
</div>
{% if feature_page.page_intro %}
<div class="container-fluid site-intro-section">
    <div class="row">
        <div class="col-1 col-sm-2 col-md-5 col-lg-7">
            <!-- Positioning Column -->
        </div>
        <div class="col-11 col-sm-10 col-md-7 col-lg-5 text-center transparent-text-block">
            <p>{{ feature_page.page_intro | safe}}</p>
        </div>
    </div>
</div>
{% endif %}

{% for section in feature_sections %}
<div class="container mt-2 mb-2">
    <div class="row">
        {% if forloop.counter|divisibleby:2 %}
        <div class="col-12">
            <img class="section-img section-img-right" src="{{ section.section_image.url }}"  width="100" height="100" alt="XBasic Demo Screen">
            <h3>{{ section.title }}</h3>
            <p class="article-text">{{ section.article | safe }}</p>
        </div>
        {% else %}
        <div class="col-12">
            <img class="section-img section-img-left" src="{{ section.section_image.url }}"  width="100" height="100" alt="XBasic Demo Screen">
            <h3>{{ section.title }}</h3>
            <p class="article-text">{{ section.article | safe }}</p>
        </div>
        {% endif %}
    </div>
</div>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% endblock content %}

templates/issue_control.html
<div class="row">
    {% if type == 'issue' and num_issues > 0 or type == "answer" and num_answers > 0 %}
    <div class="col-12 text-center">
        <p>Number Found: {{ num_items }} Current Item: {{ item_num|add:1 }}</p>
    </div>
    {% else %}
    <div class="col-12 text-center">
        <p>No Items Present</p>
    </div>
    {% endif %}
</div>
<div class="row mb-1">
    {% if type == 'issue' and num_issues > 0 or type == "answer" and num_answers > 0 %}
    <div class="col-xs-4 col-sm-2 col-md-2 text-center">
        {% if item_num == 0 %}
        <a class="btn-edit-submit" href="{% url 'step_issue' issue_num=0 answer_num=0 search_field=search_field scroll_to_answer=0 scroll_delay=0 %}" aria-label="Previous">
            Prev
        </a>
        {% else %} 
            {% with item_num=item_num|add:-1 %} 
                {% if type == 'issue' %}
                <a class="btn-edit-submit" href="{% url 'step_issue' issue_num=item_num answer_num=0 search_field=search_field scroll_to_answer=0 scroll_delay=0%}" id="previousIssue" aria-label="Previous Issue">
                    Prev
                </a>
                {% else %}
                <a class="btn-edit-submit" href="{% url 'step_issue' issue_num=0 answer_num=item_num search_field=search_field scroll_to_answer=1 scroll_delay=0 %}" id="previousAnswer" aria-label="Previous Answer">
                    Prev
                </a>
                {% endif %}
            {% endwith %}
        {% endif %}
    </div>
    {% else %}
    <div class="col-2"></div>
    {% endif %}

    {% if user.is_superuser %}
        {% if num_items > 0 %}
        <div class="col-1"></div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'add_issue' %}" id="newIssueSuperUser" aria-label="New Issue Super-User Link">
                New
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'add_answer' issue_id=issue.id %}" id="newAnswerSuperUser" aria-label="New Answer Super-User Link">
                New
            </a>
            {% endif %}
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'edit_issue' edit=1 issue_num=issue_num search_field=search_field issue_id=issue.id %}" id="editIssueSuperUser" aria-label="Edit Issue Super-User Link">
                Edit
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'edit_answer' issue_id=issue.id answer_id=answer.id %}" id="editAnswerSuperUser" aria-label="Edit Answer Super-User Link">
                Edit
            </a>
            {% endif %}
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2">
            {% if type == "issue" %}
                <button class="btn-edit-submit" id="deleteIssueButton" aria-label="Delete Issue">Delete</button>
            {% else %}
                <button class="btn-edit-submit" id="deleteAnswerButton" aria-label="Delete Answer">Delete</button>
            {% endif %}
        </div>
        <div class="col-1"></div>
        {% else %}
        <div class="col-3"></div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'add_issue' %}" id="newIssueSuperUserNoEntries" aria-label="New Issue Super-User NoEntries">
                New
            </a>
            {% endif %}
        </div>
        <div class="col-3"></div>
        {% endif %}

    {% elif user.is_authenticated %}
        {% if num_items == 0 %}
        <div class="col-3"></div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'add_issue' %}" id="newIssueUser" aria-label="New Issue User">
                New
            </a>
            {% else %}
                {% if num_issues > 0 %}
                    <a class="btn-edit-submit" href="{% url 'add_answer' issue_id=issue.id %}" id="newAnswerUser" aria-label="New Answer User">
                        New
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <div class="col-5"></div>
        {% elif type == "issue" and issue.author.username == user.username or type == "answer" and answer.author.username == user.username %}
        <div class="col-sm-1"></div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'add_issue' %}" id="newIssueUser" aria-label="New Issue User">
                New
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'add_answer' issue_id=issue.id %}" id="newAnswerUser" aria-label="New Answer User">
                New
            </a>
            {% endif %}
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'edit_issue' edit=1 issue_num=issue_num search_field=search_field issue_id=issue.id %}" id="editIssueUser" aria-label="Edit Issue User">
                Edit
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'edit_answer' issue_id=issue.id answer_id=answer.id %}" id="editAnswerUser" aria-label="Edit Answer User">
                Edit
            </a>
            {% endif %}
        </div>
        <div class="col-xs-4 col-sm-2 col-md-2">
            {% if type == "issue" %}
                <button class="btn-edit-submit" id="deleteIssueButton" aria-label="Delete Issue">Delete</button>
            {% else %}
                <button class="btn-edit-submit" id="deleteAnswerButton" aria-label="Delete Answer">Delete</button>
            {% endif %}
        </div>
        <div class="col-sm-1"></div>
        {% else %}
        <div class="col-3"></div>
        <div class="col-xs-4 col-sm-2 col-md-2 text-center">
            {% if type == "issue" %}
            <a class="btn-edit-submit" href="{% url 'add_issue' %}" id="newIssueUserNoEntries" aria-label="New Issue User No Entries">
                New
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'add_answer' issue_id=issue.id %}" id="newAnswerUserNoEntries" aria-label="New Answer User No Entries">
                New
            </a>
            {% endif %}
        </div>
        <div class="col-3"></div>
        {% endif %}
       
    {% else %}
     <div class="col-xs-0 col-sm-8"></div>
    {% endif %}

    {% if type == 'issue' and num_issues > 0 or type == "answer" and num_answers > 0 %}
    <div class="col-xs-4 col-sm-2 col-md-2 text-center">
        {% with item_num=item_num|add:1 %}
            {% if type == 'issue' %}
            <a class="btn-edit-submit" href="{% url 'step_issue' issue_num=item_num answer_num=0 search_field=search_field scroll_to_answer=0 scroll_delay=0 %}" id="nextIssue" aria-label="Next Issue">
                Next
            </a>
            {% else %}
            <a class="btn-edit-submit" href="{% url 'step_issue' issue_num=issue_num answer_num=item_num search_field=search_field scroll_to_answer=1 scroll_delay=0 %}" id="nextAnswer" aria-label="Next Answer">
                Next
            </a>
            {% endif %}
        {% endwith %}
    </div>
    {% endif %}

</div>

  
<script>
    {% if type == 'issue' %}
        if ("{{ num_items }}" > 0) {
            var issueId = "{{ issue.id }}";
            {% if issue %}
                var deleteIssueUrl = "{% url 'delete_issue' issue_id=issue.id %}";
            {% endif %}
        }
    {% endif %}

    {% if answer %}
        var deleteAnswerUrl = "{% url 'delete_answer' issue_id=issue.id answer_id=answer.id %}";
    {% endif %}
    var deleteItemUrl = ""; // Global for alternative value
    var answerId = "{{ answer.id }}";
</script>

templates/issue_panel.html
<div class="container-fluid issue_panel mb-3">
    <div class="row">
        <div class="col-12 col-md-6">
            <p><strong>Title: </strong>{{ issue.title }}</p>
            <p><strong>Description: </strong>{{ issue.description }}</p>
        </div>
        <div class="col-md-1"></div>
        <div class="col-12 col-md-5 text-md-right">
            <p><strong>Author: </strong>{{ issue.author }}</p>
            <p><strong>Date: </strong>{{ issue.date_submitted|date:"d/m/Y" }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <p><strong>Keywords: </strong>{{ issue.keywords }}</p>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-12 text-center">
            <p><strong>CONTENT</strong></p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ issue.content|safe }}
        </div>
    </div>
    {% if 'placeholder' not in issue.screenshot_img.url %}
    <div class="row">
        <div class="col-12">
            <img class="screenshot-img" src="{{ issue.screenshot_img.url }}" width="100" height="100" alt="Screenshot">
        </div>
    </div>
    {% endif %}

</div>

templates/issues.html
{% extends "base.html" %}

{% block content %}
    <div class="container" id="issuesContainer">
        <div class="row">
            <div class="col-12 text-center page-heading">
                <h2>XBasic Issues, Problems and Answers</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="issue-header">Issue</h3>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12 text-center">
                <form action="{% url 'issue_display' %}" method="get">
                    {% if search_field == "X" %}
                    <input class="issue-search" name="issue_search" type="text" 
                        placeholder="Title, Description or Keyword words">
                    {% else %}
                    <input class="issue-search" name="issue_search" type="text" 
                        value="{{ search_field }}">
                    {% endif %}
                    <button class="btn-submit" type="submit" aria-label="Search Submit">
                        <i class="fas fa-search search-icon"></i>
                    </button>
                </form>
            </div>
        </div>

        {% include 'issue_control.html' with type="issue" record=issue num_items=num_issues item_num=issue_num %}

        {% if not user.is_authenticated %}
        <div class="row">
            <div class="col-10 offset-1 alert alert-warning text-center" role="alert">
                Please register/login in order to add an issue or answer
            </div>
        </div>
        {% endif %}
        {% include "issue_panel.html" with issue=issue %}

        <!-- Answer Section -->
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="issue-header" id="answerTitle">Answers</h3>
            </div>
        </div>
        {% include 'issue_control.html' with type="answer" record=answer num_items=num_answers item_num=answer_num %}

        {% include 'answer_panel.html' with answer=answer %}
        
        <!-- Modal for delete operation -->
        <!-- for the corresponding script see base.html  -->
        <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content delete-modal">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmTitle" aria-label="Confirmation">Confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to proceed?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <button type="button" class="btn btn-primary" id="confirmButton">Yes</button>
                    </div>
                </div>
            </div>
        </div>

        <script>
            {% if scroll_to_answer == 1 %}
            var scroll_to_answer = true;
            var scroll_delay = {{ scroll_delay }}
            {% endif %}
        </script>
    </div>

{% endblock content %}